#spring.mvc.pathmatch.matching-strategy=ant_path_matcher

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: DkeU5Zupd4S7W5VQ43pQ
    secret: 6SiQBcArny

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher